services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kupi_podari_day_frontend
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
