version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kpd_frontend
    ports:
      - "8081:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kpd_server
    ports:
      - "4000:3000"
    depends_on:
      - database
    env_file:
      - .env

  database:
    container_name: kpd_db
    restart: always
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - PG_DATABASE:${POSTGRES_PGDATA}

networks:
  app-network:
    driver: bridge
volumes:
  PG_DATABASE:
